/*
 * Spedition.de REST API
 *  ## Authorization  Authorization is done with an API token submitted in the authorization header of your request.  `Authorization: Bearer <token>`  ## Date and time format Timezone: Dependent on your account settings. Defaults to `Europe/Berlin`. * **Date** = *Y-m-d* = `2021-01-01` * **Time** = *H:i* = `10:14` * **Date & time** = Y-m-d\\TH:i:sP = `2020-12-09T16:09:53+00:00` or any RFC 3339 compliant date time format.
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ListMetaLinks} from './ListMetaLinks';

/**
 * The ListMeta model module.
 * @module model/ListMeta
 * @version 1.0.5
 */
export class ListMeta {
  /**
   * Constructs a new <code>ListMeta</code>.
   * @alias module:model/ListMeta
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ListMeta</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ListMeta} obj Optional instance to populate.
   * @return {module:model/ListMeta} The populated <code>ListMeta</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ListMeta();
      if (data.hasOwnProperty('current_page'))
        obj.currentPage = ApiClient.convertToType(data['current_page'], 'Number');
      if (data.hasOwnProperty('from'))
        obj.from = ApiClient.convertToType(data['from'], 'Number');
      if (data.hasOwnProperty('last_page'))
        obj.lastPage = ApiClient.convertToType(data['last_page'], 'Number');
      if (data.hasOwnProperty('path'))
        obj.path = ApiClient.convertToType(data['path'], 'String');
      if (data.hasOwnProperty('per_page'))
        obj.perPage = ApiClient.convertToType(data['per_page'], 'Number');
      if (data.hasOwnProperty('to'))
        obj.to = ApiClient.convertToType(data['to'], 'Number');
      if (data.hasOwnProperty('total'))
        obj.total = ApiClient.convertToType(data['total'], 'Number');
      if (data.hasOwnProperty('links'))
        obj.links = ApiClient.convertToType(data['links'], [ListMetaLinks]);
    }
    return obj;
  }
}

/**
 * @member {Number} currentPage
 */
ListMeta.prototype.currentPage = undefined;

/**
 * @member {Number} from
 */
ListMeta.prototype.from = undefined;

/**
 * @member {Number} lastPage
 */
ListMeta.prototype.lastPage = undefined;

/**
 * @member {String} path
 */
ListMeta.prototype.path = undefined;

/**
 * @member {Number} perPage
 */
ListMeta.prototype.perPage = undefined;

/**
 * @member {Number} to
 */
ListMeta.prototype.to = undefined;

/**
 * @member {Number} total
 */
ListMeta.prototype.total = undefined;

/**
 * @member {Array.<module:model/ListMetaLinks>} links
 */
ListMeta.prototype.links = undefined;

