/*
 * Spedition.de REST API
 *  ## Authorization  Authorization is done with an API token submitted in the authorization header of your request.  `Authorization: Bearer <token>`  ## Date and time format Timezone: Dependent on your account settings. Defaults to `Europe/Berlin`. * **Date** = *Y-m-d* = `2021-01-01` * **Time** = *H:i* = `10:14` * **Date & time** = Y-m-d\\TH:i:sP = `2020-12-09T16:09:53+00:00` or any RFC 3339 compliant date time format.
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ListMetaLinks model module.
 * @module model/ListMetaLinks
 * @version 1.0.5
 */
export class ListMetaLinks {
  /**
   * Constructs a new <code>ListMetaLinks</code>.
   * @alias module:model/ListMetaLinks
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ListMetaLinks</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ListMetaLinks} obj Optional instance to populate.
   * @return {module:model/ListMetaLinks} The populated <code>ListMetaLinks</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ListMetaLinks();
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
      if (data.hasOwnProperty('active'))
        obj.active = ApiClient.convertToType(data['active'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} url
 */
ListMetaLinks.prototype.url = undefined;

/**
 * @member {String} label
 */
ListMetaLinks.prototype.label = undefined;

/**
 * @member {Boolean} active
 */
ListMetaLinks.prototype.active = undefined;

