/*
 * Spedition.de REST API
 *  ## Authorization  Authorization is done with an API token submitted in the authorization header of your request.  `Authorization: Bearer <token>`  ## Date and time format Timezone: Dependent on your account settings. Defaults to `Europe/Berlin`. * **Date** = *Y-m-d* = `2021-01-01` * **Time** = *H:i* = `10:14` * **Date & time** = Y-m-d\\TH:i:sP = `2020-12-09T16:09:53+00:00` or any RFC 3339 compliant date time format.
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ListLinks model module.
 * @module model/ListLinks
 * @version 1.0.5
 */
export class ListLinks {
  /**
   * Constructs a new <code>ListLinks</code>.
   * @alias module:model/ListLinks
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ListLinks</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ListLinks} obj Optional instance to populate.
   * @return {module:model/ListLinks} The populated <code>ListLinks</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ListLinks();
      if (data.hasOwnProperty('first'))
        obj.first = ApiClient.convertToType(data['first'], 'String');
      if (data.hasOwnProperty('last'))
        obj.last = ApiClient.convertToType(data['last'], 'String');
      if (data.hasOwnProperty('prev'))
        obj.prev = ApiClient.convertToType(data['prev'], 'String');
      if (data.hasOwnProperty('next'))
        obj.next = ApiClient.convertToType(data['next'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} first
 */
ListLinks.prototype.first = undefined;

/**
 * @member {String} last
 */
ListLinks.prototype.last = undefined;

/**
 * @member {String} prev
 */
ListLinks.prototype.prev = undefined;

/**
 * @member {String} next
 */
ListLinks.prototype.next = undefined;

