/*
 * Spedition.de REST API
 *  ## Authorization  Authorization is done with an API token submitted in the authorization header of your request.  `Authorization: Bearer <token>`  ## Date and time format Timezone: Dependent on your account settings. Defaults to `Europe/Berlin`. * **Date** = *Y-m-d* = `2021-01-01` * **Time** = *H:i* = `10:14` * **Date & time** = Y-m-d\\TH:i:sP = `2020-12-09T16:09:53+00:00` or any RFC 3339 compliant date time format.
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ListLinks} from './ListLinks';
import {ListMeta} from './ListMeta';
import {Order} from './Order';

/**
 * The OrderCollection model module.
 * @module model/OrderCollection
 * @version 1.0.5
 */
export class OrderCollection {
  /**
   * Constructs a new <code>OrderCollection</code>.
   * @alias module:model/OrderCollection
   * @class
   * @extends 
   */
  constructor() {
  }

  /**
   * Constructs a <code>OrderCollection</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderCollection} obj Optional instance to populate.
   * @return {module:model/OrderCollection} The populated <code>OrderCollection</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderCollection();
      ApiClient.constructFromObject(data, obj, '');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [Order]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Order>} data
 */
OrderCollection.prototype.data = undefined;

