/*
 * Spedition.de REST API
 *  ## Authorization  Authorization is done with an API token submitted in the authorization header of your request.  `Authorization: Bearer <token>`  ## Date and time format Timezone: Dependent on your account settings. Defaults to `Europe/Berlin`. * **Date** = *Y-m-d* = `2021-01-01` * **Time** = *H:i* = `10:14` * **Date & time** = Y-m-d\\TH:i:sP = `2020-12-09T16:09:53+00:00` or any RFC 3339 compliant date time format.
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The OrderDetail model module.
 * @module model/OrderDetail
 * @version 1.0.5
 */
export class OrderDetail {
  /**
   * Constructs a new <code>OrderDetail</code>.
   * @alias module:model/OrderDetail
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OrderDetail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderDetail} obj Optional instance to populate.
   * @return {module:model/OrderDetail} The populated <code>OrderDetail</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderDetail();
      if (data.hasOwnProperty('number'))
        obj._number = ApiClient.convertToType(data['number'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'Number');
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'Number');
      if (data.hasOwnProperty('ean'))
        obj.ean = ApiClient.convertToType(data['ean'], 'String');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} _number
 */
OrderDetail.prototype._number = undefined;

/**
 * @member {String} name
 */
OrderDetail.prototype.name = undefined;

/**
 * @member {Number} price
 */
OrderDetail.prototype.price = undefined;

/**
 * @member {Number} quantity
 */
OrderDetail.prototype.quantity = undefined;

/**
 * @member {String} ean
 */
OrderDetail.prototype.ean = undefined;

/**
 * @member {String} image
 */
OrderDetail.prototype.image = undefined;

