/*
 * Spedition.de REST API
 *  ## Authorization  Authorization is done with an API token submitted in the authorization header of your request.  `Authorization: Bearer <token>`  ## Date and time format Timezone: Dependent on your account settings. Defaults to `Europe/Berlin`. * **Date** = *Y-m-d* = `2021-01-01` * **Time** = *H:i* = `10:14` * **Date & time** = Y-m-d\\TH:i:sP = `2020-12-09T16:09:53+00:00` or any RFC 3339 compliant date time format.
 *
 * OpenAPI spec version: 1.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {OrderDetail} from './OrderDetail';

/**
 * The Order model module.
 * @module model/Order
 * @version 1.0.5
 */
export class Order {
  /**
   * Constructs a new <code>Order</code>.
   * @alias module:model/Order
   * @class
   * @param ordernumber {String} 
   * @param firstname {String} 
   * @param lastname {String} 
   * @param street {String} 
   * @param zip {String} 
   * @param city {String} 
   * @param country {String} 
   */
  constructor(ordernumber, firstname, lastname, street, zip, city, country) {
    this.ordernumber = ordernumber;
    this.firstname = firstname;
    this.lastname = lastname;
    this.street = street;
    this.zip = zip;
    this.city = city;
    this.country = country;
  }

  /**
   * Constructs a <code>Order</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Order} obj Optional instance to populate.
   * @return {module:model/Order} The populated <code>Order</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Order();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('module'))
        obj.module = ApiClient.convertToType(data['module'], 'String');
      if (data.hasOwnProperty('ordernumber'))
        obj.ordernumber = ApiClient.convertToType(data['ordernumber'], 'String');
      if (data.hasOwnProperty('ordertime'))
        obj.ordertime = ApiClient.convertToType(data['ordertime'], 'Date');
      if (data.hasOwnProperty('firstname'))
        obj.firstname = ApiClient.convertToType(data['firstname'], 'String');
      if (data.hasOwnProperty('lastname'))
        obj.lastname = ApiClient.convertToType(data['lastname'], 'String');
      if (data.hasOwnProperty('company'))
        obj.company = ApiClient.convertToType(data['company'], 'String');
      if (data.hasOwnProperty('department'))
        obj.department = ApiClient.convertToType(data['department'], 'String');
      if (data.hasOwnProperty('street'))
        obj.street = ApiClient.convertToType(data['street'], 'String');
      if (data.hasOwnProperty('zip'))
        obj.zip = ApiClient.convertToType(data['zip'], 'String');
      if (data.hasOwnProperty('city'))
        obj.city = ApiClient.convertToType(data['city'], 'String');
      if (data.hasOwnProperty('country'))
        obj.country = ApiClient.convertToType(data['country'], 'String');
      if (data.hasOwnProperty('phone'))
        obj.phone = ApiClient.convertToType(data['phone'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('shipping_vendor'))
        obj.shippingVendor = ApiClient.convertToType(data['shipping_vendor'], 'String');
      if (data.hasOwnProperty('details'))
        obj.details = ApiClient.convertToType(data['details'], [OrderDetail]);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Order.prototype.id = undefined;

/**
 * @member {String} module
 */
Order.prototype.module = undefined;

/**
 * @member {String} ordernumber
 */
Order.prototype.ordernumber = undefined;

/**
 * @member {Date} ordertime
 */
Order.prototype.ordertime = undefined;

/**
 * @member {String} firstname
 */
Order.prototype.firstname = undefined;

/**
 * @member {String} lastname
 */
Order.prototype.lastname = undefined;

/**
 * @member {String} company
 */
Order.prototype.company = undefined;

/**
 * @member {String} department
 */
Order.prototype.department = undefined;

/**
 * @member {String} street
 */
Order.prototype.street = undefined;

/**
 * @member {String} zip
 */
Order.prototype.zip = undefined;

/**
 * @member {String} city
 */
Order.prototype.city = undefined;

/**
 * @member {String} country
 */
Order.prototype.country = undefined;

/**
 * @member {String} phone
 */
Order.prototype.phone = undefined;

/**
 * @member {String} email
 */
Order.prototype.email = undefined;

/**
 * @member {Number} amount
 */
Order.prototype.amount = undefined;

/**
 * Allowed values for the <code>shippingVendor</code> property.
 * @enum {String}
 * @readonly
 */
Order.ShippingVendorEnum = {
  /**
   * value: "cargo-international"
   * @const
   */
  cargoInternational: "cargo-international",

  /**
   * value: "dhl"
   * @const
   */
  dhl: "dhl",

  /**
   * value: "ups"
   * @const
   */
  ups: "ups",

  /**
   * value: "gel-express"
   * @const
   */
  gelExpress: "gel-express",

  /**
   * value: "dsv"
   * @const
   */
  dsv: "dsv"
};
/**
 * Preselect your installed shipping vendor
 * @member {module:model/Order.ShippingVendorEnum} shippingVendor
 */
Order.prototype.shippingVendor = undefined;

/**
 * @member {Array.<module:model/OrderDetail>} details
 */
Order.prototype.details = undefined;

